# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0004_horarionut_duracion'),
        ('nutricion', '0003_auto_20170818_1816'),
    ]

    operations = [
    ]
